### ISSUE TITLE
Allow HTTP transport servers to use path opt if present

### ISSUE THREAD

**Issue by AnActualEmerald** [earthstar-project/earthstar-streaming-rpc#17]
## What's the problem you want solved?
[transport-http-server-opine](https://github.com/earthstar-project/earthstar-streaming-rpc/blob/main/src/transport-http-server-opine.ts) (and -express) currently hijack all of the routes of the opine/express app that is passed into the constructor

## Is there a solution you'd like to recommend?
Use the `path` opt if it exists and if not default to the wildcard

**Comment by sgwilym** [comment]
Thanks for catching this! This should be fixed as of v5.0.0.
