### ISSUE TITLE
RPC: how to import express in Deno (or use opine?)

### ISSUE THREAD

**Issue by cinnamon-bun** [earthstar-project/earthstar-streaming-rpc#5]
Help set up the project so it imports `express` in node, but [`opine`](https://deno.land/x/opine@2.1.1) in deno.  Hopefully they are similar enough that our basic usage of them will work in both cases.

Nothing is importing this yet, it will be part of `TransportHttpServer` when that is written.

**Comment by sgwilym** [comment]
Closed by #11!
